# -*- coding: utf-8 -*-
# Generated by tools/gen_implementation.py. DO NOT EDIT MANUALLY.
# This file imports generated ezcolors functions and provides a list for tests.

import sys

# Attempt to import from the main ezcolors module
# This assumes ezcolors is installed or src is in PYTHONPATH when tests run
try:
    from ezcolors import (
        bg_black,
    bg_blue,
    bg_bright_black,
    bg_bright_blue,
    bg_bright_cyan,
    bg_bright_green,
    bg_bright_magenta,
    bg_bright_red,
    bg_bright_white,
    bg_bright_yellow,
    bg_cyan,
    bg_green,
    bg_magenta,
    bg_red,
    bg_white,
    bg_yellow,
    blink,
    blink_rapid,
    blue,
    bold,
    cyan,
    dim,
    fail,
    fg_black,
    fg_blue,
    fg_bright_black,
    fg_bright_blue,
    fg_bright_cyan,
    fg_bright_green,
    fg_bright_magenta,
    fg_bright_red,
    fg_bright_white,
    fg_bright_yellow,
    fg_cyan,
    fg_green,
    fg_magenta,
    fg_red,
    fg_white,
    fg_yellow,
    green,
    header,
    hidden,
    inverse,
    italic,
    red,
    strikethrough,
    underline,
    warning
    )
    _IMPORT_SUCCESS = True
except ImportError as e:
    # Provide a helpful message if ezcolors isn't installed/found
    print(f"ERROR in /home/cfrbal/Code/python_exercies/ezcolors/ezcolors/tools/gen.py: Failed to import functions from 'ezcolors'.", file=sys.stderr)
    print("Ensure 'ezcolors' is installed correctly (e.g., 'pip install -e .').", file=sys.stderr)
    print(f"Original error: {e}", file=sys.stderr)
    _IMPORT_SUCCESS = False
    # Define empty list so importing file doesn't crash tests immediately
    functions_to_test = []


# List of functions for pytest parametrization
# This list is only populated if the imports above succeeded.
functions_to_test = [
    bg_black,
    bg_blue,
    bg_bright_black,
    bg_bright_blue,
    bg_bright_cyan,
    bg_bright_green,
    bg_bright_magenta,
    bg_bright_red,
    bg_bright_white,
    bg_bright_yellow,
    bg_cyan,
    bg_green,
    bg_magenta,
    bg_red,
    bg_white,
    bg_yellow,
    blink,
    blink_rapid,
    blue,
    bold,
    cyan,
    dim,
    fail,
    fg_black,
    fg_blue,
    fg_bright_black,
    fg_bright_blue,
    fg_bright_cyan,
    fg_bright_green,
    fg_bright_magenta,
    fg_bright_red,
    fg_bright_white,
    fg_bright_yellow,
    fg_cyan,
    fg_green,
    fg_magenta,
    fg_red,
    fg_white,
    fg_yellow,
    green,
    header,
    hidden,
    inverse,
    italic,
    red,
    strikethrough,
    underline,
    warning
] if _IMPORT_SUCCESS else []
